### ISSUE TITLE
Interested in pull requests?

### ISSUE THREAD

**Issue by hamishmb** [michaelgchu/Cygwin_Specific_Repo#1]
I'm using your bundle script for packaging my program and have some ideas for improvements that I'm going to code sometime soon.

I wondering if you're interested in pull requests to get the changes here?

**Comment by michaelgchu** [comment]
Yes please. I am very curious to see what the changes are. (TBH I haven't
used that script lately, but still interested to see!)

Thanks
Michael

**Comment by hamishmb** [comment]
Excellent :)

I'll close this issue for now, and then once I've got my changes done (might be a week or so), I'll open some pull requests.
