### ISSUE TITLE
Extra scripts under BSD license by Marco Atzeri from the Cygwin project

### ISSUE THREAD

**Issue by hamishmb** [michaelgchu/Cygwin_Specific_Repo#4]
I have a couple of useful scripts that are potential candidates to be added here. Both were written by Marco Atzeri from the Cygwin project.

One lists the binary packages for a DLL and its dependencies, similar to your Cygwin DLL/EXE bundling script.

The other script makes it easy to dump all installed packages and makes a batch script to reinstall Cygwin with all the packages you had before - useful for migration.

These are both available under the BSD license. I know the existing scripts here are Unlicense, but if you're interested, would it be okay to add an extra LICENSE file for these ones too? I have found the reinstallation script useful on a number of occasions.

Hamish

**Comment by hamishmb** [comment]
Never mind, available and hosted with permission at https://gitlab.com/hamishmb/cygwin-scripts

**Comment by michaelgchu** [comment]
Apologies! I was busy when this notification came in and decided to set it aside to handle later, obviously far too late.
Tbh, I'm not clear on the differences between the various licenses, so I was going to take some time to understand BSD vs Unlicense and how to add more for specific items in the repo.

**Comment by hamishmb** [comment]
No problem!

I would put anything under a different license in a subfolder with attribution and another LICENSE file inside, with the main README pointing it out. Still happy to get them in here if you like, but I don't mind.

**Comment by michaelgchu** [comment]
OK, well I certainly don't mind hosting some additional files here.  Will
you be submitting this as another pull request?

**Comment by hamishmb** [comment]
Yeah, that's what I'll do. Are you happy for me to do that?

After that I'll let the author of the scripts know it's here as well so he can double check he's okay with everything (I have already asked him for permission).

**Comment by michaelgchu** [comment]
Yes, please do. It'll be nice to these related scripts all gathered in one
convenient spot
